import mods.thaumcraft.ArcaneWorkbench;
val gemLatex = <ore:gemLatex>;
gemLatex.remove(<hbm:ball_resin>);
val ingotAnyRubber = <ore:ingotAnyRubber>;
ingotAnyRubber.remove(<gregtech:meta_ingot:1068>);
ingotAnyRubber.remove(<hbm:ingot_biorubber>);
ingotAnyRubber.add(<gregtech:meta_ingot:1004>);
val ingotOsmiridium = <ore:ingotOsmiridium>;
ingotOsmiridium.remove(<gregtech:meta_ingot:344>);
val nuggetOsmiridium = <ore:nuggetOsmiridium>;
nuggetOsmiridium.remove(<gregtech:meta_nugget:344>);
val dustOsmiridium = <ore:dustOsmiridium>;
dustOsmiridium.remove(<gregtech:meta_dust:344>);
val ingotBronze = <ore:ingotBronze>;
ingotBronze.remove(<lucraftcore:ingot_bronze>);
ingotBronze.remove(<thermalfoundation:material:163>);
ingotBronze.remove(<mekanism:ingot:2>);
val ingotTin = <ore:ingotTin>;
ingotTin.remove(<lucraftcore:ingot_tin>);
ingotTin.remove(<thermalfoundation:material:129>);
ingotTin.remove(<mekanism:ingot:6>);
ingotTin.remove(<alchemistry:ingot:50>);
val ingotCopper = <ore:ingotCopper>;
ingotCopper.remove(<lucraftcore:ingot_copper>);
ingotCopper.remove(<thermalfoundation:material:128>);
ingotCopper.remove(<mekanism:ingot:5>);
ingotCopper.remove(<alchemistry:ingot:29>);
ingotCopper.remove(<immersiveengineering:metal:0>);
ingotCopper.remove(<hbm:ingot_copper>);
val ingotSilver = <ore:ingotSilver>;
ingotSilver.remove(<lucraftcore:ingot_silver>);
ingotSilver.remove(<iceandfire:silver_ingot>);
ingotSilver.remove(<thermalfoundation:material:130>);
ingotSilver.remove(<immersiveengineering:metal:3>);
val ingotNickel = <ore:ingotNickel>;
ingotNickel.remove(<lucraftcore:ingot_nickel>);
ingotNickel.remove(<thermalfoundation:material:133>);
ingotNickel.remove(<galaxyspace:ingots:2>);
ingotNickel.remove(<alchemistry:ingot:28>);
ingotNickel.remove(<immersiveengineering:metal:4>);
val ingotLead = <ore:ingotLead>;
ingotLead.remove(<lucraftcore:ingot_lead>);
ingotLead.remove(<thermalfoundation:material:131>);
ingotLead.remove(<hbm:ingot_lead>);
ingotLead.remove(<alchemistry:ingot:82>);
ingotLead.remove(<immersiveengineering:metal:2>);
val ingotTitanium = <ore:ingotTitanium>;
ingotTitanium.remove(<lucraftcore:ingot_titanium>);
ingotTitanium.remove(<hbm:ingot_titanium>);
ingotTitanium.remove(<mekanismecoenergistics:moreingot:1>);
ingotTitanium.remove(<alchemistry:ingot:22>);
val ingotOsmium = <ore:ingotOsmium>;
ingotOsmium.remove(<lucraftcore:ingot_osmium>);
ingotOsmium.remove(<mekanism:ingot:1>);
ingotOsmium.remove(<alchemistry:ingot:76>);
val ingotIridium = <ore:ingotIridium>;
ingotIridium.remove(<lucraftcore:ingot_iridium>);
ingotIridium.remove(<thermalfoundation:material:135>);
ingotIridium.remove(<alchemistry:ingot:77>);
ingotIridium.remove(<mekanismecoenergistics:moreingot:3>);
val ingotUranium = <ore:ingotUranium>;
ingotUranium.remove(<lucraftcore:ingot_uranium>);
ingotUranium.remove(<bigreactors:ingotyellorium>);
ingotUranium.remove(<alchemistry:ingot:92>);
ingotUranium.remove(<hbm:ingot_uranium>);
ingotUranium.remove(<mekanismecoenergistics:moreingot:2>);
ingotUranium.remove(<immersiveengineering:metal:5>);
val ingotSteel = <ore:ingotSteel>;
ingotSteel.remove(<lucraftcore:ingot_steel>);
ingotSteel.remove(<hbm:ingot_steel>);
ingotSteel.remove(<bigreactors:ingotsteel>);
ingotSteel.remove(<thermalfoundation:material:160>);
ingotSteel.remove(<mekanism:ingot:4>);
ingotSteel.remove(<industrialrenewal:ingot_steel>);
ingotSteel.remove(<immersiveengineering:metal:8>);
val ingotTungsten = <ore:ingotTungsten>;
ingotTungsten.remove(<hbm:ingot_tungsten>);
val ingotAluminium = <ore:ingotAluminium>;
ingotAluminium.remove(<hbm:ingot_aluminium>);
val ingotAluminum = <ore:ingotAluminum>;
ingotAluminum.remove(<thermalfoundation:material:132>);
ingotAluminum.remove(<alchemistry:ingot:13>);
ingotAluminum.remove(<immersiveengineering:metal:1>);
val ingotPlatinum = <ore:ingotPlatinum>;
ingotPlatinum.remove(<thermalfoundation:material:134>);
ingotPlatinum.remove(<alchemistry:ingot:78>);
val ingotElectrum = <ore:ingotElectrum>;
ingotElectrum.remove(<thermalfoundation:material:161>);
ingotElectrum.remove(<immersiveengineering:metal:7>);
val ingotMagnesinum = <ore:ingotMagnesinum>;
ingotMagnesinum.remove(<alchemistry:ingot:12>);
val ingotConstantan = <ore:ingotConstantan>;
ingotConstantan.remove(<immersiveengineering:metal:6>);
val ingotInvar = <ore:ingotInvar>;
ingotInvar.remove(<thermalfoundation:material:162>);
ingotInvar.remove(<plustic:invaringot>);
val ingotTantalum = <ore:ingotTantalum>;
ingotTantalum.remove(<hbm:ingot_tantalium>);
ingotTantalum.remove(<alchemistry:ingot:73>);
val ingotPlutonium = <ore:ingotPlutonium>;
ingotPlutonium.remove(<bigreactors:ingotblutonium>);
ingotPlutonium.remove(<hbm:ingot_plutonium>);
ingotPlutonium.remove(<alchemistry:ingot:94>);
val ingotPlutonium241 = <ore:ingotPlutonium241>;
ingotPlutonium241.remove(<gregtech:meta_ingot:82>);
val ingotPalladium = <ore:iningotPalladium>;
ingotPalladium.remove(<lucraftcore:ingot_palladium>);
val ingotCobalt = <ore:ingotCobalt>;
ingotCobalt.remove(<tconstruct:ingots:0>);
ingotCobalt.remove(<gregtech:meta_ingot:23>);
ingotCobalt.remove(<alchemistry:ingot:27>);
ingotCobalt.remove(<galaxyspace:ingots:0>);
val ingotUranium238 = <ore:ingotUranium238>;
ingotUranium238.remove(<hbm:ingot_u238>);
val ingotUranium235 = <ore:ingotUranium235>;
ingotUranium235.remove(<hbm:ingot_u235>);
val ingotBrass = <ore:ingotBrass>;
ingotBrass.remove(<gregtech:meta_ingot:259>);
val ingotCesium = <ore:ingotCesium>;
ingotCesium.remove(<alchemistry:ingot:55>);
val ingotBeryllium = <ore:ingotBeryllium>;
ingotBeryllium.remove(<alchemistry:ingot:4>);
ingotBeryllium.remove(<hbm:ingot_beryllium>);
val ingotPolonium = <ore:ingotPolonium>;
ingotPolonium.remove(<alchemistry:ingot:84>);
val ingotStrontium = <ore:ingotStrontium>;
ingotStrontium.remove(<alchemistry:ingot:38>);
val ingotAstatine = <ore:ingotAstatine>;
ingotAstatine.remove(<alchemistry:ingot:85>);
val ingotLanthanum = <ore:ingotLanthanum>;
ingotLanthanum.remove(<alchemistry:ingot:57>);
val ingotCerium = <ore:ingotCerium>;
ingotCerium.remove(<alchemistry:ingot:58>);
val ingotActinium = <ore:ingotActinium>;
ingotActinium.remove(<alchemistry:ingot:89>);
val ingotNiobium = <ore:ingotNiobium>;
ingotNiobium.remove(<alchemistry:ingot:41>);
ingotNiobium.remove(<gregtech:meta_ingot:71>);
val ingotTennessine = <ore:ingotTennessine>;
ingotTennessine.remove(<alchemistry:ingot:117>);
val ingotNeptunium = <ore:ingotNeptunium>;
ingotNeptunium.remove(<alchemistry:ingot:93>);
val ingotThorium = <ore:ingotThorium>;
ingotThorium.remove(<alchemistry:ingot:90>);
ingotThorium.remove(<gregtech:meta_ingot:109>);
val ingotArsenic = <ore:ingotArsenic>;
ingotArsenic.remove(<alchemistry:ingot:33>);
val ingotCadmium = <ore:ingotCadmium>;
ingotCadmium.remove(<alchemistry:ingot:48>);
val stickSteel = <ore:stickSteel>;
stickSteel.remove(<industrialrenewal:stick_steel>);
val stickIron = <ore:stickIron>;
stickIron.remove(<industrialrenewal:stick_iron>);
val oreIron = <ore:oreIron>;
oreIron.remove(<industrialrenewal:orevein_hematite>);
oreIron.remove(<industrialrenewal:chunk_hematite>);
val oreLignite = <ore:oreLignite>;
oreLignite.remove(<hbm:ore_lignite>);
val blockSteel = <ore:blockSteel>;
blockSteel.remove(<lucraftcore:block_steel>);
blockSteel.remove(<thermalfoundation:storage_alloy:0>);
blockSteel.remove(<mekanism:basicblock:5>);
blockSteel.remove(<industrialrenewal:block_steel>);
blockSteel.remove(<immersiveengineering:storage:8>);
<recipemap:assembler>.findRecipe(7, [<metaitem:foilCopper> * 4, <metaitem:plateWood>], [<liquid:glue> * 100]).remove();
<recipemap:chemical_reactor>.findRecipe(30, [<metaitem:foilSilver> * 4, <metaitem:board.phenolic>], [<liquid:iron_iii_chloride> * 100]).remove();
<recipemap:chemical_reactor>.findRecipe(30, [<metaitem:foilSilver> * 4, <metaitem:board.phenolic>], [<liquid:sodium_persulfate> * 200]).remove();
<recipemap:assembler>.findRecipe(30, [<metaitem:dustWood>, <metaitem:circuit.integrated>.withTag({Configuration: 1})], [<liquid:glue> * 50]).remove();
<recipemap:large_chemical_reactor>.findRecipe(30, [<metaitem:foilSilver> * 4, <metaitem:board.phenolic>], [<liquid:sodium_persulfate> * 200]).remove();
<recipemap:large_chemical_reactor>.findRecipe(30, [<metaitem:foilSilver> * 4, <metaitem:board.phenolic>], [<liquid:iron_iii_chloride> * 100]).remove();
<recipemap:chemical_reactor>.findRecipe(10, [<metaitem:platePlastic>, <metaitem:foilCopper> * 4], [<liquid:sulfuric_acid> * 250]).remove();
<recipemap:chemical_reactor>.findRecipe(10, [<metaitem:platePolyvinylChloride>, <metaitem:foilCopper> * 4], [<liquid:sulfuric_acid> * 250]).remove();
<recipemap:chemical_reactor>.findRecipe(10, [<metaitem:platePolytetrafluoroethylene>, <metaitem:foilCopper> * 4], [<liquid:sulfuric_acid> * 250]).remove();
<recipemap:chemical_reactor>.findRecipe(10, [<metaitem:platePolybenzimidazole>, <metaitem:foilCopper> * 4], [<liquid:sulfuric_acid> * 250]).remove();
<recipemap:large_chemical_reactor>.findRecipe(10, [<metaitem:platePlastic>, <metaitem:foilCopper> * 4], [<liquid:sulfuric_acid> * 250]).remove();
<recipemap:large_chemical_reactor>.findRecipe(10, [<metaitem:platePolyvinylChloride>, <metaitem:foilCopper> * 4], [<liquid:sulfuric_acid> * 250]).remove();
<recipemap:large_chemical_reactor>.findRecipe(10, [<metaitem:platePolytetrafluoroethylene>, <metaitem:foilCopper> * 4], [<liquid:sulfuric_acid> * 250]).remove();
<recipemap:large_chemical_reactor>.findRecipe(10, [<metaitem:platePolybenzimidazole>, <metaitem:foilCopper> * 4], [<liquid:sulfuric_acid> * 250]).remove();
<recipemap:chemical_reactor>.findRecipe(30, [<metaitem:plateEpoxy>, <metaitem:foilGold> * 8], [<liquid:sulfuric_acid> * 500]).remove();
mods.ntm.DFC.removeRecipe(<hbm:machine_fensu>);
mods.ntm.Assembler.removeRecipe(<hbm:machine_fensu>);
mods.ntm.Assembler.replaceRecipe(<hbm:machine_schrabidium_transmutator>, [<gregtech:meta_ingot:115> * 5, <gregtech:meta_ingot:113> * 24, <hbm:plate_advanced_alloy> * 18, <gregtech:meta_plate:324> * 12, <hbm:plate_desh> * 6, <hbm:ingot_rubber> * 8, <hbm:machine_battery> * 5, <hbm:circuit_gold> * 5], 60);
mods.ntm.Assembler.addRecipe(<hbm:machine_tower_large>, [<hbm:concrete_smooth> * 128, <hbm:steel_scaffold> * 32, <hbm:machine_condenser> * 25, <hbm:pipes_steel> * 2], 30);
mods.ntm.Assembler.addRecipe(<hbm:machine_tower_small>, [<hbm:brick_concrete> * 64, <minecraft:iron_bars> * 128, <hbm:machine_condenser> * 5], 30);
mods.ntm.Assembler.addRecipe(<hbm:red_pylon_large>, [<hbm:concrete_smooth> * 2, <hbm:steel_scaffold> * 8, <hbm:plate_polymer> * 8, <hbm:coil_copper> * 4], 30);
mods.ntm.Assembler.addRecipe(<hbm:substation>, [<hbm:concrete_smooth> * 6, <hbm:steel_scaffold> * 2, <hbm:plate_polymer> * 8, <hbm:coil_copper> * 2, <hbm:coil_copper_torus> * 2, <gregtech:meta_ingot:324> * 4], 30);
mods.ntm.Assembler.addRecipe(<hbm:machine_deuterium_tower>, [<hbm:concrete_smooth> * 12, <hbm:steel_scaffold> * 16, <hbm:deuterium_filter> * 2, <hbm:hull_big_steel> * 5, <hbm:deco_pipe_quad> * 12, <gregtech:meta_dust:103> * 32], 30);
mods.ntm.Assembler.addRecipe(<hbm:heater_firebox>, [<minecraft:furnace>, <gregtech:meta_plate:324> * 8, <gregtech:meta_ingot:252> * 8], 30);
mods.ntm.Assembler.addRecipe(<hbm:heater_oven>, [<hbm:ingot_firebrick> * 16, <gregtech:meta_plate:324> * 8, <gregtech:meta_ingot:252> * 8], 30);
mods.ntm.Assembler.addRecipe(<hbm:heater_heatex>, [<hbm:ingot_rubber>, <gregtech:meta_plate:324> * 16, <gregtech:meta_ingot:252> * 16, <hbm:pipes_steel>], 30);
mods.ntm.Assembler.addRecipe(<hbm:heater_oilburner>, [<gregtech:meta_ingot:113> * 12, <hbm:tank_steel> * 4, <gregtech:meta_ingot:252> * 8, <hbm:pipes_steel>], 30);
mods.ntm.Assembler.addRecipe(<hbm:heater_electric>, [<gregtech:meta_plate:324> * 8, <hbm:ingot_polymer> * 4, <gregtech:meta_ingot:252> * 8, <hbm:coil_tungsten> * 8, <hbm:circuit_copper>], 30);
mods.ntm.Assembler.addRecipe(<hbm:heater_rt>, [<gregtech:meta_plate:324> * 8, <hbm:ingot_tcalloy> * 6, <gregtech:meta_ingot:252> * 16, <hbm:rtg_unit> * 5, <hbm:neutron_reflector> * 8], 30);
mods.ntm.Assembler.addRecipe(<hbm:furnace_steel>, [<gregtech:meta_plate:324> * 16, <minecraft:stonebrick> * 16, <gregtech:meta_ingot:25> * 12, <hbm:steel_grate> * 16], 30);
mods.ntm.Assembler.addRecipe(<hbm:heat_boiler>, [<gregtech:meta_ingot:324> * 4, <gregtech:meta_plate:252> * 16, <hbm:plate_polymer> * 8], 30);
mods.ntm.Assembler.addRecipe(<hbm:machine_deuterium_extractor>, [<gregtech:meta_plate:324> * 4, <gregtech:meta_plate:2> * 2, <hbm:board_copper>, <hbm:turbine_titanium>, <hbm:circuit_aluminium>, <hbm:hull_small_steel> * 4, <gregtech:meta_dust:103> * 8], 30);
mods.ntm.BlastFurnace.addRecipe(<hbm:ingot_steel_dusted:0>, <hbm:ingot_steel_dusted:0>, <hbm:ingot_steel_dusted:1>);
mods.ntm.BlastFurnace.addRecipe(<hbm:ingot_steel_dusted:1>, <hbm:ingot_steel_dusted:1>, <hbm:ingot_steel_dusted:2>);
mods.ntm.BlastFurnace.addRecipe(<hbm:ingot_steel_dusted:2>, <hbm:ingot_steel_dusted:2>, <hbm:ingot_steel_dusted:3>);
mods.ntm.BlastFurnace.addRecipe(<hbm:ingot_steel_dusted:3>, <hbm:ingot_steel_dusted:3>, <hbm:ingot_steel_dusted:4>);
mods.ntm.BlastFurnace.addRecipe(<hbm:ingot_steel_dusted:4>, <hbm:ingot_steel_dusted:4>, <hbm:ingot_steel_dusted:5>);
mods.ntm.BlastFurnace.addRecipe(<hbm:ingot_steel_dusted:5>, <hbm:ingot_steel_dusted:5>, <hbm:ingot_steel_dusted:6>);
mods.ntm.BlastFurnace.addRecipe(<hbm:ingot_steel_dusted:6>, <hbm:ingot_steel_dusted:6>, <hbm:ingot_steel_dusted:7>);
mods.ntm.BlastFurnace.addRecipe(<hbm:ingot_steel_dusted:7>, <hbm:ingot_steel_dusted:7>, <hbm:ingot_steel_dusted:8>);
mods.ntm.BlastFurnace.addRecipe(<hbm:ingot_steel_dusted:8>, <hbm:ingot_steel_dusted:8>, <hbm:ingot_steel_dusted:9>);
mods.ntm.BlastFurnace.addRecipe(<hbm:ingot_steel_dusted:9>, <hbm:ingot_steel_dusted:9>, <hbm:ingot_chainsteel>);
mods.ntm.BlastFurnace.addRecipe(<hbm:ingot_meteorite>, <hbm:ingot_meteorite>, <hbm:ingot_meteorite_forged>);
mods.ntm.BlastFurnace.addRecipe(<hbm:ingot_meteorite_forged>, <hbm:ingot_meteorite_forged>, <hbm:blade_meteorite>);
mods.ntm.BlastFurnace.addRecipe(<hbm:meteorite_sword_seared>, <hbm:ingot_meteorite_forged>, <hbm:meteorite_sword_reforged>);
mods.thaumcraft.ArcaneWorkbench.removeRecipe(<thaumcraft:infusion_matrix>);
mods.thaumcraft.ArcaneWorkbench.registerShapedRecipe("test", "", 150, [<aspect:aer>, <aspect:ignis>, <aspect:terra>, <aspect:perditio>, <aspect:aqua>, <aspect:ordo>], <thaumcraft:infusion_matrix>, [[<thaumcraft:matrix_speed>, <hbm:nuke_gadget>, <thaumcraft:matrix_speed>], [<thaumcraft:plate:2>, <gregtech:machine:112>, <thaumcraft:plate:2>], [<thaumcraft:matrix_cost>, <hbm:hadron_access>, <thaumcraft:matrix_cost>]]);
mods.tconstruct.Casting.removeTableRecipe(<tconstruct:cast_custom:0>);
mods.tconstruct.Casting.removeTableRecipe(<tconstruct:cast_custom:1>);
mods.tconstruct.Casting.removeTableRecipe(<tconstruct:cast_custom:3>);
mods.tconstruct.Casting.removeTableRecipe(<tconstruct:cast_custom:4>);
mods.jei.JEI.removeAndHide(<hbm:machine_fensu>);
mods.jei.JEI.removeAndHide(<gregtech:meta_ingot:344>);
mods.jei.JEI.removeAndHide(<gregtech:meta_dust:344>);
mods.jei.JEI.removeAndHide(<gregtech:meta_ingot_hot:344>);
mods.jei.JEI.removeAndHide(<gregtech:meta_item_1:382>);
mods.jei.JEI.removeAndHide(<gregtech:meta_item_1:381>);
mods.jei.JEI.removeAndHide(<hbm:block_tungsten>);
mods.jei.JEI.removeAndHide(<hbm:block_beryllium>);
mods.jei.JEI.removeAndHide(<hbm:block_niobium>);
mods.jei.JEI.removeAndHide(<hbm:block_lead>);
mods.jei.JEI.removeAndHide(<hbm:block_steel>);
mods.jei.JEI.removeAndHide(<hbm:block_aluminium>);
mods.jei.JEI.removeAndHide(<hbm:block_copper>);
mods.jei.JEI.removeAndHide(<hbm:block_titanium>);
mods.jei.JEI.removeAndHide(<hbm:block_uranium>);
mods.jei.JEI.removeAndHide(<hbm:block_pu239>);
mods.jei.JEI.removeAndHide(<hbm:block_sulfur>);
mods.jei.JEI.removeAndHide(<hbm:block_niter>);
mods.jei.JEI.removeAndHide(<hbm:ore_nether_uranium>);
mods.jei.JEI.removeAndHide(<hbm:ore_nether_sulfur>);
mods.jei.JEI.removeAndHide(<hbm:ore_nether_cobalt>);
mods.jei.JEI.removeAndHide(<hbm:ore_nether_tungsten>);
mods.jei.JEI.removeAndHide(<hbm:ore_nether_uranium_scorched>);
mods.jei.JEI.removeAndHide(<hbm:ore_nether_plutonium>);
mods.jei.JEI.removeAndHide(<hbm:ore_meteor_uranium>);
mods.jei.JEI.removeAndHide(<hbm:ore_meteor_thorium>);
mods.jei.JEI.removeAndHide(<hbm:ore_meteor_titanium>);
mods.jei.JEI.removeAndHide(<hbm:ore_meteor_sulfur>);
mods.jei.JEI.removeAndHide(<hbm:ore_meteor_copper>);
mods.jei.JEI.removeAndHide(<hbm:ore_meteor_tungsten>);
mods.jei.JEI.removeAndHide(<hbm:ore_meteor_aluminium>);
mods.jei.JEI.removeAndHide(<hbm:ore_meteor_lead>);
mods.jei.JEI.removeAndHide(<hbm:ore_uranium>);
mods.jei.JEI.removeAndHide(<hbm:ore_uranium_scorched>);
mods.jei.JEI.removeAndHide(<hbm:ore_thorium>);
mods.jei.JEI.removeAndHide(<hbm:ore_titanium>);
mods.jei.JEI.removeAndHide(<hbm:ore_sulfur>);
mods.jei.JEI.removeAndHide(<hbm:ore_niter>);
mods.jei.JEI.removeAndHide(<hbm:ore_copper>);
mods.jei.JEI.removeAndHide(<hbm:ore_tungsten>);
mods.jei.JEI.removeAndHide(<hbm:ore_aluminium>);
mods.jei.JEI.removeAndHide(<hbm:ore_lead>);
mods.jei.JEI.removeAndHide(<hbm:ore_asbestos>);
mods.jei.JEI.removeAndHide(<hbm:ore_cobalt>);
mods.jei.JEI.removeAndHide(<hbm:cluster_titanium>);
mods.jei.JEI.removeAndHide(<hbm:cluster_iron>);
mods.jei.JEI.removeAndHide(<hbm:cluster_aluminium>);
mods.jei.JEI.removeAndHide(<hbm:cluster_copper>);
mods.jei.JEI.removeAndHide(<hbm:ore_gneiss_iron>);
mods.jei.JEI.removeAndHide(<hbm:ore_gneiss_gold>);
mods.jei.JEI.removeAndHide(<hbm:ore_gneiss_uranium>);
mods.jei.JEI.removeAndHide(<hbm:ore_gneiss_copper>);
mods.jei.JEI.removeAndHide(<hbm:ore_gneiss_asbestos>);
mods.jei.JEI.removeAndHide(<hbm:ore_gneiss_lithium>);
mods.jei.JEI.removeAndHide(<hbm:ore_gneiss_uranium_scorched>);
mods.jei.JEI.removeAndHide(<hbm:coke>);
mods.jei.JEI.removeAndHide(<hbm:ball_resin>);
mods.jei.JEI.removeAndHide(<hbm:block_cobalt>);
mods.jei.JEI.removeAndHide(<hbm:deco_beryllium>);
mods.jei.JEI.removeAndHide(<hbm:deco_lead>);
mods.jei.JEI.removeAndHide(<hbm:deco_steel>);
mods.jei.JEI.removeAndHide(<hbm:deco_aluminium>);
mods.jei.JEI.removeAndHide(<hbm:deco_tungsten>);
mods.jei.JEI.removeAndHide(<hbm:deco_titanium>);
mods.jei.JEI.removeAndHide(<teslacorelib:machine_case>);
mods.jei.JEI.removeAndHide(<iceandfire:silver_ingot>);
mods.jei.JEI.removeAndHide(<hbm:ingot_steel>);
mods.jei.JEI.removeAndHide(<hbm:ingot_biorubber>);
mods.jei.JEI.removeAndHide(<hbm:ingot_titanium>);
mods.jei.JEI.removeAndHide(<hbm:ingot_tungsten>);
mods.jei.JEI.removeAndHide(<hbm:ingot_aluminium>);
mods.jei.JEI.removeAndHide(<lucraftcore:ingot_silver>);
mods.jei.JEI.removeAndHide(<lucraftcore:ingot_copper>);
mods.jei.JEI.removeAndHide(<lucraftcore:ingot_tin>);
mods.jei.JEI.removeAndHide(<lucraftcore:ingot_nickel>);
mods.jei.JEI.removeAndHide(<lucraftcore:ingot_lead>);
mods.jei.JEI.removeAndHide(<lucraftcore:ingot_titanium>);
mods.jei.JEI.removeAndHide(<lucraftcore:ingot_osmium>);
mods.jei.JEI.removeAndHide(<lucraftcore:ingot_iridium>);
mods.jei.JEI.removeAndHide(<lucraftcore:ingot_bronze>);
mods.jei.JEI.removeAndHide(<lucraftcore:ingot_uranium>);
mods.jei.JEI.removeAndHide(<lucraftcore:ingot_steel>);
mods.jei.JEI.removeAndHide(<lucraftcore:ingot_palladium>);
mods.jei.JEI.removeAndHide(<lucraftcore:nugget_silver>);
mods.jei.JEI.removeAndHide(<lucraftcore:nugget_copper>);
mods.jei.JEI.removeAndHide(<lucraftcore:nugget_tin>);
mods.jei.JEI.removeAndHide(<lucraftcore:nugget_nickel>);
mods.jei.JEI.removeAndHide(<lucraftcore:nugget_lead>);
mods.jei.JEI.removeAndHide(<lucraftcore:nugget_titanium>);
mods.jei.JEI.removeAndHide(<lucraftcore:nugget_osmium>);
mods.jei.JEI.removeAndHide(<lucraftcore:nugget_iridium>);
mods.jei.JEI.removeAndHide(<lucraftcore:nugget_bronze>);
mods.jei.JEI.removeAndHide(<lucraftcore:nugget_uranium>);
mods.jei.JEI.removeAndHide(<lucraftcore:nugget_steel>);
mods.jei.JEI.removeAndHide(<lucraftcore:nugget_palladium>);
mods.jei.JEI.removeAndHide(<lucraftcore:plate_silver>);
mods.jei.JEI.removeAndHide(<lucraftcore:plate_copper>);
mods.jei.JEI.removeAndHide(<lucraftcore:plate_tin>);
mods.jei.JEI.removeAndHide(<lucraftcore:plate_nickel>);
mods.jei.JEI.removeAndHide(<lucraftcore:plate_lead>);
mods.jei.JEI.removeAndHide(<lucraftcore:plate_titanium>);
mods.jei.JEI.removeAndHide(<lucraftcore:plate_osmium>);
mods.jei.JEI.removeAndHide(<lucraftcore:plate_iridium>);
mods.jei.JEI.removeAndHide(<lucraftcore:plate_bronze>);
mods.jei.JEI.removeAndHide(<lucraftcore:plate_uranium>);
mods.jei.JEI.removeAndHide(<lucraftcore:plate_steel>);
mods.jei.JEI.removeAndHide(<lucraftcore:plate_palladium>);
mods.jei.JEI.removeAndHide(<lucraftcore:dust_silver>);
mods.jei.JEI.removeAndHide(<lucraftcore:dust_copper>);
mods.jei.JEI.removeAndHide(<lucraftcore:dust_tin>);
mods.jei.JEI.removeAndHide(<lucraftcore:dust_nickel>);
mods.jei.JEI.removeAndHide(<lucraftcore:dust_lead>);
mods.jei.JEI.removeAndHide(<lucraftcore:dust_titanium>);
mods.jei.JEI.removeAndHide(<lucraftcore:dust_osmium>);
mods.jei.JEI.removeAndHide(<lucraftcore:dust_iridium>);
mods.jei.JEI.removeAndHide(<lucraftcore:dust_bronze>);
mods.jei.JEI.removeAndHide(<lucraftcore:dust_uranium>);
mods.jei.JEI.removeAndHide(<lucraftcore:dust_steel>);
mods.jei.JEI.removeAndHide(<lucraftcore:dust_palladium>);
mods.jei.JEI.removeAndHide(<lucraftcore:ore_silver>);
mods.jei.JEI.removeAndHide(<lucraftcore:ore_copper>);
mods.jei.JEI.removeAndHide(<lucraftcore:ore_tin>);
mods.jei.JEI.removeAndHide(<lucraftcore:ore_nickel>);
mods.jei.JEI.removeAndHide(<lucraftcore:ore_lead>);
mods.jei.JEI.removeAndHide(<lucraftcore:ore_titanium>);
mods.jei.JEI.removeAndHide(<lucraftcore:ore_osmium>);
mods.jei.JEI.removeAndHide(<lucraftcore:ore_iridium>);
mods.jei.JEI.removeAndHide(<lucraftcore:ore_uranium>);
mods.jei.JEI.removeAndHide(<lucraftcore:ore_palladium>);
mods.jei.JEI.removeAndHide(<lucraftcore:infinity_generator>);
mods.jei.JEI.removeAndHide(<tconstruct:cast_custom:0>);
mods.jei.JEI.removeAndHide(<tconstruct:cast_custom:1>);
mods.jei.JEI.removeAndHide(<tconstruct:cast_custom:3>);
mods.jei.JEI.removeAndHide(<tconstruct:cast_custom:4>);
mods.jei.JEI.removeAndHide(<tconstruct:casting:1>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:337>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:304>);
mods.jei.JEI.removeAndHide(<galacticraftcore:basic_item:3>);
mods.jei.JEI.removeAndHide(<galacticraftcore:basic_item:4>);
mods.jei.JEI.removeAndHide(<galacticraftcore:basic_item:5>);
mods.jei.JEI.removeAndHide(<galacticraftplanets:basic_item_venus:1>);
mods.jei.JEI.removeAndHide(<galacticraftplanets:item_basic_asteroids:0>);
mods.jei.JEI.removeAndHide(<bigreactors:ingotyellorium>);
mods.jei.JEI.removeAndHide(<bigreactors:ingotblutonium>);
mods.jei.JEI.removeAndHide(<bigreactors:ingotsteel>);
mods.jei.JEI.removeAndHide(<bigreactors:ingotgraphite>);
mods.jei.JEI.removeAndHide(<bigreactors:dustyellorium>);
mods.jei.JEI.removeAndHide(<bigreactors:dustblutonium>);
mods.jei.JEI.removeAndHide(<bigreactors:duststeel>);
mods.jei.JEI.removeAndHide(<bigreactors:blocksteel>);
mods.jei.JEI.removeAndHide(<bigreactors:dustyellorium>);
mods.jei.JEI.removeAndHide(<bigreactors:dustgraphite>);
mods.jei.JEI.removeAndHide(<bigreactors:blockyellorium>);
mods.jei.JEI.removeAndHide(<bigreactors:blockblutonium>);
mods.jei.JEI.removeAndHide(<bigreactors:dustcyanite>);
mods.jei.JEI.removeAndHide(<bigreactors:dustludicrite>);
mods.jei.JEI.removeAndHide(<bigreactors:mineralbenitoite>);
mods.jei.JEI.removeAndHide(<bigreactors:mineralanglesite>);
mods.jei.JEI.removeAndHide(<bigreactors:orebenitoite>);
mods.jei.JEI.removeAndHide(<bigreactors:oreanglesite>);
mods.jei.JEI.removeAndHide(<bigreactors:turbinehousingcores>);
mods.jei.JEI.removeAndHide(<bigreactors:reactorcasingcores>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:288>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:290>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:291>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:260>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:24>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:772>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:1024>);
mods.jei.JEI.removeAndHide(<hbm:niter>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:802>);
mods.jei.JEI.removeAndHide(<hbm:coke>);
mods.jei.JEI.removeAndHide(<thermalfoundation:storage_resource:1>);
mods.jei.JEI.removeAndHide(<hbm:block_coke>);
mods.jei.JEI.removeAndHide(<jurassicraft:iron_rod>);
mods.jei.JEI.removeAndHide(<industrialrenewal:stick_iron>);
mods.jei.JEI.removeAndHide(<industrialrenewal:stick_steel>);
mods.jei.JEI.removeAndHide(<industrialrenewal:orevein_hematite>);
mods.jei.JEI.removeAndHide(<industrialrenewal:chunk_hematite>);
mods.jei.JEI.removeAndHide(<industrialrenewal:sponge_iron>);
mods.jei.JEI.removeAndHide(<industrialrenewal:ingot_steel>);
mods.jei.JEI.removeAndHide(<industrialrenewal:lathe>);
mods.jei.JEI.removeAndHide(<industrialrenewal:drill_deep>);
mods.jei.JEI.removeAndHide(<hbm:anvil_iron>);
mods.jei.JEI.removeAndHide(<hbm:anvil_lead>);
mods.jei.JEI.removeAndHide(<hbm:anvil_meteorite>);
mods.jei.JEI.removeAndHide(<hbm:anvil_starmetal>);
mods.jei.JEI.removeAndHide(<hbm:anvil_ferrouranium>);
mods.jei.JEI.removeAndHide(<hbm:anvil_bismuth>);
mods.jei.JEI.removeAndHide(<hbm:anvil_schrabidate>);
mods.jei.JEI.removeAndHide(<hbm:anvil_dnt>);
mods.jei.JEI.removeAndHide(<hbm:anvil_osmiridium>);
mods.jei.JEI.removeAndHide(<hbm:anvil_murky>);
mods.jei.JEI.removeAndHide(<hbm:ore_lignite>);
mods.jei.JEI.removeAndHide(<hbm:lignite>);
mods.jei.JEI.removeAndHide(<hbm:briquette_lignite>);
mods.jei.JEI.removeAndHide(<hbm:block_lignite>);
mods.jei.JEI.removeAndHide(<hbm:powder_lignite>);
mods.jei.JEI.removeAndHide(<pneumaticcraft:refinery>);
mods.jei.JEI.removeAndHide(<pneumaticcraft:thermopneumatic_processing_plant>);
mods.jei.JEI.removeAndHide(<minecraft:wooden_pickaxe>);
mods.jei.JEI.removeAndHide(<minecraft:wooden_shovel>);
mods.jei.JEI.removeAndHide(<minecraft:wooden_hoe>);
mods.jei.JEI.removeAndHide(<minecraft:wooden_axe>);
mods.jei.JEI.removeAndHide(<minecraft:wooden_sword>);
mods.jei.JEI.removeAndHide(<minecraft:stone_pickaxe>);
mods.jei.JEI.removeAndHide(<minecraft:stone_shovel>);
mods.jei.JEI.removeAndHide(<minecraft:stone_hoe>);
mods.jei.JEI.removeAndHide(<minecraft:stone_axe>);
mods.jei.JEI.removeAndHide(<minecraft:stone_sword>);